# Platform.sh Project Initialization Template
#
# This file defines settings and workflow modifications that allow a git
# repository to be deployed to Platform.sh and its white-label partners. A
# project template can be a fully functioning ready-made application or a
# quick-start point for custom development work.
#
# It contains elements that affect the behaviour upon the initialisation of
# a new project (for example minimal plan sizes) as well as elements that
# allow Platform.sh to present it in a user interface (such as the description
# of the project, tags, an icon etc.).
#
# Once provisioned this file has no effects on the running project.  You
# are free to remove it.

# The schema is versioned so that we can establish code paths differently in the future if we need to change this.
version: 1

# Templates are a small amount of information supporting a template URL. Each template is selectable at the project-creation step.
info:
  # Unique machine name, prefaced by a vendor or organization identifier
  id: platformsh/wordpress
  # The human-readable name of the template.
  name: Wordpress
  # Human-readable descriptive text for the template. Supports limited HTML.
  description: WordPress is the world's most widely used lightweight CMS and blogging tool.
  # A list of tags associated with the template.
  tags:
  - PHP
  - WordPress
  - CMS
  # An image URI (either base64-encoded or a URL) representing the template.
  image: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4KPCEtLSBHZW5lcmF0b3I6IEFkb2JlIElsbHVzdHJhdG9yIDIzLjAuMSwgU1ZHIEV4cG9ydCBQbHVnLUluIC4gU1ZHIFZlcnNpb246IDYuMDAgQnVpbGQgMCkgIC0tPgo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzEiIHhtbG5zOnJkZj0iaHR0cDovL3d3dy53My5vcmcvMTk5OS8wMi8yMi1yZGYtc3ludGF4LW5zIyIKCSB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHhtbG5zOnhsaW5rPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5L3hsaW5rIiB4PSIwcHgiIHk9IjBweCIgdmlld0JveD0iMCAwIDQwIDQwIgoJIHN0eWxlPSJlbmFibGUtYmFja2dyb3VuZDpuZXcgMCAwIDQwIDQwOyIgeG1sOnNwYWNlPSJwcmVzZXJ2ZSI+CjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+Cgkuc3Qwe2ZpbGwtcnVsZTpldmVub2RkO2NsaXAtcnVsZTpldmVub2RkO2ZpbGw6IzQ2NDM0Mjt9Cjwvc3R5bGU+CjxnIHRyYW5zZm9ybT0ibWF0cml4KDEuMDc1NSAwIDAgMS4wNzU1IC0zLjUxMDMgLTEuNjY4NCkiPgoJPHBhdGggY2xhc3M9InN0MCIgZD0iTTIxLjksMy4xYzQuNCwwLDguNSwxLjcsMTEuNSw0LjVjLTEuNSwwLTMsMC44LTMsMi45Yy0wLjEsNC4xLDQuOSw1LDIuMiwxMy4ybC0yLjIsNi44bC02LjEtMTcuOQoJCWMtMC4xLTAuMywwLTAuNCwwLjQtMC40aDEuN2MwLjEsMCwwLjItMC4xLDAuMi0wLjJ2LTFjMC0wLjEtMC4xLTAuMi0wLjItMC4yYy0zLjMsMC4xLTYuNSwwLjEtOS43LDBjLTAuMSwwLTAuMiwwLjEtMC4yLDAuMnYxCgkJYzAsMC4xLDAuMSwwLjIsMC4yLDAuMmgxLjdjMC40LDAsMC41LDAuMSwwLjYsMC40bDIuNSw2LjhsLTMuOCwxMS4zbC02LjItMTguMmMtMC4xLTAuMiwwLTAuNCwwLjItMC40aDJjMC4xLDAsMC4yLTAuMSwwLjItMC4ydi0xCgkJYzAtMC4xLTAuMS0wLjItMC4yLTAuMmMtMi4xLDAuMS00LjEsMC4xLTYuMSwwLjJDMTAuNiw2LjIsMTUuOSwzLjEsMjEuOSwzLjFMMjEuOSwzLjFMMjEuOSwzLjF6IE0zNi44LDEyLjFjMS4zLDIuNCwyLDUuMiwyLDguMQoJCWMwLDYuNC0zLjYsMTItOC44LDE0LjlsNS4zLTE1QzM2LjEsMTcuNywzNi45LDE0LjYsMzYuOCwxMi4xTDM2LjgsMTIuMUwzNi44LDEyLjF6IE0yNy42LDM2LjJjLTEuOCwwLjYtMy43LDEtNS43LDEKCQljLTEuNywwLTMuNC0wLjMtNC45LTAuN2w1LjItMTVMMjcuNiwzNi4yTDI3LjYsMzYuMkwyNy42LDM2LjJ6IE0xNC42LDM1LjVjLTUuNy0yLjctOS43LTguNi05LjctMTUuNGMwLTIuNSwwLjUtNC45LDEuNS03LjEKCQlMMTQuNiwzNS41TDE0LjYsMzUuNUwxNC42LDM1LjV6IE0yMS45LDEuNmMxMC4zLDAsMTguNiw4LjMsMTguNiwxOC42cy04LjMsMTguNi0xOC42LDE4LjZTMy4zLDMwLjQsMy4zLDIwLjFTMTEuNiwxLjYsMjEuOSwxLjZ6IgoJCS8+CjwvZz4KPC9zdmc+Cg==
  
  # Additional notes displayed in the template's detail view.
  # Each note object is displayed as a small section heading with content below. Supports limited HTML.
  notes:
    - heading: "Apps & Services"
      content: "PHP 7.2<br/>MySQL 10.2"


# This key describes the initialization call made to the master environment at
# project creation time. This is part of the full v2 UI operation mode, which
# places project schema/options selection early in the creation process, rather
# than later as it exitss now. To allow this schema to be backwards-compatible,
# this key also gets mapped to the appropriate location in project.settings so
# that the current UI can have its own workflow overridden as well.
initialize:
  repository: git://github.com/platformsh/template-wordpress.git@master
  config: null
  files: []
  profile: Wordpress
